apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.config.all.name }}
  labels:
    app: {{ .Values.config.all.labels.app }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/appinfo/prometheus"
    prometheus.io/port: "8080"
spec:
  selector:
    app: {{ .Values.config.all.labels.app }}
  ports:
    - name: http
      port: 8080
      targetPort: http
