---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.config.all.name }}
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/elevenproof-configmap.yaml") . | sha256sum }}
  labels:
    app: {{ .Values.config.all.labels.app }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.config.all.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.config.all.labels.app }}
    spec:
      containers:
        - image: {{ .Values.config.app.container.image }}
          imagePullPolicy: IfNotPresent
          name: {{ .Values.config.all.name }}
          ports:
            - name: http
              containerPort: 8080
          securityContext:
            runAsNonRoot: false
            readOnlyRootFilesystem: false # need for /tmp folder to work in spring boot
          resources:
            limits:
              cpu: 750m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 1Gi
          livenessProbe:
            httpGet:
              path: /appinfo/health/liveness
              port: 8080
            failureThreshold: 6
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /appinfo/health/liveness
              port: 8080
            failureThreshold: 30
            periodSeconds: 10
          volumeMounts:
            - name: app-config
              mountPath: /app/config/application.yaml
              subPath: application.yaml
              readOnly: true
            - name: app-secrets
              readOnly: true
              mountPath: /private-keys/
          env:
            - name: JAVA_OPTS
              value: ""
      volumes:
        - name: app-config
          configMap:
            name: {{ .Values.config.all.name }}-configmap
        - name: app-secrets
          secret:
            secretName: {{ .Values.config.all.name }}-secrets
            items:
              - key: elevenproof-rest-api
                path: elevenproof-rest-api/private_key
