kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.config.all.name }}-configmap
data:
  application.yaml: |
    spring:
      profiles:
        active: dev
      main:
        banner-mode: "off"
        log-startup-info: "off"