apiVersion: v1
kind: Service
metadata:
  name: elevenproof-service
spec:
  selector:
    app: elevenproof
  ports:
    - name: eleven-port
      port: 8080
      targetPort: 8080
      nodePort: 30088
  type: NodePort
